### ISSUE TITLE
Is stream reads resource only once?

### ISSUE THREAD

**Issue by Maximilan4** [reactphp/stream#142]
Hello, i am running loop as a single process, and trying to read STDIN for commands parsing.
`$in = new ReadableResourceStream(fopen('php://stdin', 'rb'), $this->loop);`
`$in->on('data', function ($data) use ($in) {`
`$commands = explode('.', $data);`
`$in->close();`
`});`

All things are good, but for me it works for a single time. I am using a periodic timer for wrapping this process. Is it correct ?

**Comment by clue** [comment]
Hi @Maximilan4, welcome to ReactPHP! :tada: 

The `$in->close()` call will close the underlying resource, so the next time you try to instantiate this class, it would try to operate on an already closed resource.

As an alternative, I would suggest assigning this stream only once, i.e. outside of your periodic timer. This way you can simply react to the `data` event whenever you see fit. I also think this makes more sense from an application design perspective, because the user might send console input at any point during your program execution.

FWIW, if you're dealing with STDIO streams, I would highly recommend taking a look at https://github.com/clue/reactphp-stdio

I hope this helps :+1:
