### ISSUE TITLE
fread(): SSL: Connection reset by peer

### ISSUE THREAD

**Issue by DangerLifter** [reactphp/stream#18]
I've pretty complex application which has stable crashes. I couldn't provide any exact code or use case because crashes happens few times in several hours and I still can't catch problematic situation (if it exists at all). But crashes are:
```
exception 'ErrorException' with message 'fread(): SSL: Connection reset by peer' in /home/projects/Scraper/vendor/react/stream/src/Stream.php:121
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'fread(): SSL: C...', '/home/projects/...', 121, Array)
#1 /home/projects/Scraper/vendor/react/stream/src/Stream.php(121): fread(Resource id #374608, 4096)
#2 [internal function]: React\Stream\Stream->handleData(Resource id #374608, Object(React\EventLoop\LibEventLoop))
#3 /home/projects/Scraper/vendor/react/event-loop/LibEventLoop.php(335): call_user_func(Array, Resource id #374608, Object(React\EventLoop\LibEventLoop))
#4 [internal function]: React\EventLoop\LibEventLoop->React\EventLoop\{closure}(Resource id #374608, 2, NULL)
#5 /home/projects/Scraper/vendor/react/event-loop/LibEventLoop.php(211): event_base_loop(Resource id #113, 1)
#6 /home/projects/Scraper/library/DomainScrapper/Worker/Main.php(146): React\EventLoop\LibEventLoop->run()
#7 /home/projects/Scraper/library/DomainScrapper/Worker/Manager.php(933): DomainScrapper\Worker\Main->run(Array)
#8 /home/projects/Scraper/app/commands/WorkerRun.php(44): DomainScrapper\Worker\Manager::run('Crawler-2', '40/0/0/0')
#9 /home/projects/Scraper/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): WorkerRun->fire()
#10 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/projects/Scraper/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(WorkerRun), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/projects/Scraper/crawler(20): Symfony\Component\Console\Application->run()
#16 {main} [] []
```
Probably question is "Who is reponsible for correct processing this exception, stream itself or library that uses stream"?

**Comment by cboden** [comment]
Can you post the output of `composer show -i` please?

**Comment by clue** [comment]
Thanks for spotting! :+1: 

The `fwrite()` call in the `Buffer` does catch stream errors, while the `fread()` in the `Stream` does not. I agree that we should emit an `error` event and *cleanly* end the stream in this case.

**Comment by edhelas** [comment]
Hi, I also have an issue on my project related to this bug.
```
PHP Warning:  fread(): SSL: Connection reset by peer in /var/www/0.9/vendor/react/stream/src/Stream.php on line 131
PHP Stack trace:
PHP   1. {main}() /var/www/0.9/linker.php:0
PHP   2. React\EventLoop\StreamSelectLoop->run() /var/www/0.9/linker.php:206
PHP   3. React\EventLoop\StreamSelectLoop->waitForStreamActivity() /var/www/0.9/vendor/react/event-loop/StreamSelectLoop.php:201
PHP   4. call_user_func:{/var/www/0.9/vendor/react/event-loop/StreamSelectLoop.php:227}() /var/www/0.9/vendor/react/event-loop/StreamSelectLoop.php:227
PHP   5. React\Stream\Stream->handleData() /var/www/0.9/vendor/react/event-loop/StreamSelectLoop.php:227
PHP   6. fread() /var/www/0.9/vendor/react/stream/src/Stream.php:131
```

**Comment by lookphp** [comment]
Hi, I also have an issue on my project related to this bug , and i don't know how to fix it . Who can help me ? I use yii1 framework , but i dont't the problem comes frmo framework . I have no idea about ssl . thank you !

Array
(
    [code] => 500
    [type] => PHP warning
    [message] => fread(): SSL: Connection reset by peer
    [file] => /home/store/webroot/protected/components/SPNS.php
    [line] => 122
    [trace] => #0 /home/store/webroot/protected/components/SPNS.php(122): fread()
#1 /home/store/webroot/protected/components/SPNS.php(110): SPNS->parsePushResponse()
#2 /home/store/webroot/protected/modules/server/controllers/AppController.php(613): SPNS->Send()
#3 /home/store/webroot/protected/modules/server/controllers/AppController.php(570): AppController->spnsPush()
#4 /home/store/framework/web/actions/CInlineAction.php(49): AppController->actionChangeStatus()
#5 /home/store/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /home/store/framework/web/filters/CFilterChain.php(133): AppController->runAction()
#7 /home/store/framework/web/filters/CFilter.php(40): CFilterChain->run()
#8 /home/store/framework/web/filters/CFilterChain.php(130): PowerCheckerFilter->filter()
#9 /home/store/framework/web/CController.php(291): CFilterChain->run()
#10 /home/store/framework/web/CController.php(265): AppController->runActionWithFilters()
#11 /home/store/framework/web/CWebApplication.php(282): AppController->run()
#12 /home/store/framework/web/CWebApplication.php(141): CWebApplication->runController()
#13 /home/store/framework/base/CApplication.php(184): CWebApplication->processRequest()
#14 /home/store/webroot/index.php(13): CWebApplication->run()

**Comment by lookphp** [comment]
Hello , I found it .
because the program can not found the path of my private key.
