### ISSUE TITLE
Any possibility to know if Stream has finished writing?

### ISSUE THREAD

**Issue by cursedcoder** [reactphp/stream#43]
In `Buffer` there's event `full-drain` but it's not proxified on `Stream` level.

**Comment by clue** [comment]
Can you elaborate on your use case for this?

(FWIW: Similar requests have been filed via #16 and #23.)

**Comment by cursedcoder** [comment]
https://github.com/cursedcoder/eprocess/blob/master/EProcess/Adapter/ChildProcess.php#L70

I'm using this to pass initial php code to interpreter and close this stream so php can execute it.

**Comment by clue** [comment]
Sounds like the perfect use case for using `end($data)` instead of `write($data)`?

The `end()` method will close the stream once the last byte has been sent.

**Comment by cursedcoder** [comment]
Another case when communicating via unix socket data should be sent synchronously and you need full-drain to schedule messages.

**Comment by clue** [comment]
I'd like to check this out, can you give a real world example on this use case?

**Comment by cursedcoder** [comment]
@clue https://github.com/cursedcoder/emessenger/commit/16230158fc7227c618874bc4361b124bb54296a1

There is a red test when I'm trying to communicate more than 1 message at time.

**Comment by clue** [comment]
I'm still curious because I've implemented quite a few protocols and have yet to come up with a reason to wait for the outgoing buffer to flush.

I'm not sure I follow this code, but it looks like the `write()`s may be mixed up (see my comment on your commit).

Can you create a simple gist to exhibit this?

**Comment by clue** [comment]
I believe this has been resolved? :shipit: 

FWIW, https://github.com/reactphp/stream/pull/16#issuecomment-71862449 also contains a possible workaround to use the `full-drain` event to check when the outgoing buffer has been flushed.

I'm closing this due to lack of feedback for now, please feel free to report back if this persists and we can reopen this :+1:
